// Deterministic summaries built only from real records. Nothing here is generated by the model,
// so the brief can never contain invented meetings or tasks. Every item carries its source id.

import type { CalendarEvent, DocumentRecord, InboxItem, Task, WaitingFor } from "./types";
import { addDays, formatTime, isSameDay, minutesBetween, toDateKey } from "./dates";
import { gapBeforeNextEvent } from "./availability";

export interface BriefInput {
  now: Date;
  tasks: Task[]; // open tasks + tasks completed recently
  waiting: WaitingFor[];
  events: CalendarEvent[]; // at least today + tomorrow
  inbox?: InboxItem[];
  documents?: DocumentRecord[];
}

export interface SourceRef {
  type: "task" | "waiting_for" | "event" | "inbox" | "document";
  id: string;
}

export interface BriefLine {
  text: string;
  ref: SourceRef;
  time?: string;
}

export interface Suggestion {
  id: string;
  kind: "follow_up" | "overdue" | "free_time" | "inbox" | "stale_task" | "follow_up_date";
  title: string;
  body: string;
  /** Prompt sent to the assistant if the user taps the suggestion. */
  prompt?: string;
  href?: string;
  refs: SourceRef[];
}

const PRIORITY_RANK = { urgent: 0, high: 1, normal: 2, low: 3 } as const;

export function plural(n: number, one: string, many: string, oneWord = "אחת"): string {
  if (n === 1) return `${one} ${oneWord}`;
  return `${n} ${many}`;
}

export function isOpen(t: Task): boolean {
  return t.status !== "completed";
}

/** Open tasks that belong to today: explicitly "today" or due today / overdue. */
export function tasksForToday(tasks: Task[], now: Date): Task[] {
  const today = toDateKey(now);
  return tasks
    .filter((t) => isOpen(t) && (t.status === "today" || (t.dueDate !== null && t.dueDate <= today)))
    .sort(compareTasks);
}

export function overdueTasks(tasks: Task[], now: Date): Task[] {
  const today = toDateKey(now);
  return tasks.filter((t) => isOpen(t) && t.dueDate !== null && t.dueDate < today);
}

export function compareTasks(a: Task, b: Task): number {
  const p = PRIORITY_RANK[a.priority] - PRIORITY_RANK[b.priority];
  if (p) return p;
  const ad = (a.dueDate ?? "9999") + (a.dueTime ?? "99");
  const bd = (b.dueDate ?? "9999") + (b.dueTime ?? "99");
  return ad < bd ? -1 : ad > bd ? 1 : 0;
}

export function eventsOn(events: CalendarEvent[], day: Date): CalendarEvent[] {
  return events.filter((e) => isSameDay(e.start, day)).sort((a, b) => a.start.getTime() - b.start.getTime());
}

export function nextEvent(events: CalendarEvent[], now: Date): CalendarEvent | null {
  return (
    events
      .filter((e) => !e.allDay && e.end > now)
      .sort((a, b) => a.start.getTime() - b.start.getTime())[0] ?? null
  );
}

export function overdueWaiting(waiting: WaitingFor[], now: Date): WaitingFor[] {
  const today = toDateKey(now);
  return waiting.filter((w) => w.status === "open" && w.expectedResponseDate !== null && w.expectedResponseDate <= today);
}

export function upcomingReminders(tasks: Task[], now: Date, hours = 24): Task[] {
  const until = now.getTime() + hours * 3600_000;
  return tasks
    .filter((t) => isOpen(t) && t.remindAt && new Date(t.remindAt).getTime() >= now.getTime() - 3600_000 && new Date(t.remindAt).getTime() <= until)
    .sort((a, b) => new Date(a.remindAt!).getTime() - new Date(b.remindAt!).getTime());
}

/** "יש לך היום 3 פגישות, 4 משימות פתוחות ופריט אחד שממתין לתשובה." */
export function homeSummary(input: BriefInput): string {
  const { now } = input;
  const meetings = eventsOn(input.events, now).filter((e) => !e.allDay && e.end > now).length;
  const tasks = tasksForToday(input.tasks, now).length;
  const waiting = overdueWaiting(input.waiting, now).length;
  const parts: string[] = [];
  if (meetings) parts.push(meetings === 1 ? "פגישה אחת" : `${meetings} פגישות`);
  if (tasks) parts.push(tasks === 1 ? "משימה פתוחה אחת" : `${tasks} משימות פתוחות`);
  if (waiting) parts.push(waiting === 1 ? "דבר אחד שממתין לתשובה" : `${waiting} דברים שממתינים לתשובה`);
  if (!parts.length) return "היום פנוי יחסית — אין פגישות או משימות דחופות.";
  const joined = parts.length === 1 ? parts[0] : `${parts.slice(0, -1).join(", ")} ו${parts[parts.length - 1]}`;
  const remaining = now.getHours() >= 14 ? "נשארו לך היום" : "יש לך היום";
  return `${remaining} ${joined}.`;
}

export function buildSuggestions(input: BriefInput): Suggestion[] {
  const { now } = input;
  const today = toDateKey(now);
  const out: Suggestion[] = [];

  for (const w of overdueWaiting(input.waiting, now).slice(0, 3)) {
    out.push({
      id: `wf:${w.id}`,
      kind: "follow_up",
      title: `${w.person} עדיין לא חזר`,
      body: `${w.person} עדיין מסומן כממתין לתשובה על "${w.subject}". רוצה שאכין הודעת follow-up?`,
      prompt: `הכן לי הודעת follow-up ל${w.person} לגבי "${w.subject}" (פריט ממתין ${w.id})`,
      refs: [{ type: "waiting_for", id: w.id }],
    });
  }

  const overdue = overdueTasks(input.tasks, now);
  if (overdue.length) {
    out.push({
      id: "overdue",
      kind: "overdue",
      title: overdue.length === 1 ? `"${overdue[0].title}" באיחור` : `${overdue.length} משימות באיחור`,
      body: "רוצה שאעזור לתזמן אותן מחדש?",
      prompt: "יש לי משימות באיחור. תציע לי איך לתזמן אותן מחדש לפי היומן שלי.",
      refs: overdue.map((t) => ({ type: "task" as const, id: t.id })),
    });
  }

  const gap = gapBeforeNextEvent(eventsOn(input.events, now), now);
  if (gap && gap.minutes >= 20 && gap.minutes <= 120) {
    const quick = tasksForToday(input.tasks, now).find((t) => (t.estimatedMinutes ?? 15) <= gap.minutes - 5);
    if (quick) {
      out.push({
        id: `gap:${gap.next.id}`,
        kind: "free_time",
        title: `${gap.minutes} דקות פנויות`,
        body: `יש לך ${gap.minutes} דקות לפני "${gap.next.title}". אולי לטפל ב"${quick.title}"?`,
        href: `/tasks/${quick.id}`,
        refs: [{ type: "event", id: gap.next.id }, { type: "task", id: quick.id }],
      });
    }
  }

  const followUps = input.tasks.filter((t) => isOpen(t) && t.followUpDate && t.followUpDate <= today);
  for (const t of followUps.slice(0, 2)) {
    out.push({
      id: `fu:${t.id}`,
      kind: "follow_up_date",
      title: `לבדוק: ${t.title}`,
      body: "הגיע מועד המעקב שקבעת למשימה הזו.",
      href: `/tasks/${t.id}`,
      refs: [{ type: "task", id: t.id }],
    });
  }

  for (const t of input.tasks.filter((t) => isOpen(t) && t.rolledOverCount >= 3).slice(0, 1)) {
    out.push({
      id: `stale:${t.id}`,
      kind: "stale_task",
      title: `"${t.title}" נדחתה ${t.rolledOverCount} פעמים`,
      body: "לפרק אותה לצעדים קטנים או להעביר ל'מתישהו'?",
      prompt: `המשימה "${t.title}" נדחית שוב ושוב. עזור לי לפרק אותה לצעד ראשון קטן.`,
      refs: [{ type: "task", id: t.id }],
    });
  }

  const newInbox = (input.inbox ?? []).filter((i) => i.status === "new");
  if (newInbox.length) {
    out.push({
      id: "inbox",
      kind: "inbox",
      title: newInbox.length === 1 ? "פריט אחד מחכה למיון" : `${newInbox.length} פריטים מחכים למיון`,
      body: "ב-Inbox יש דברים שעוד לא טופלו.",
      href: "/inbox",
      refs: newInbox.map((i) => ({ type: "inbox" as const, id: i.id })),
    });
  }
  return out;
}

export interface DailyBrief {
  date: string;
  greeting: string;
  events: BriefLine[];
  importantTasks: BriefLine[];
  waiting: BriefLine[];
  attention: BriefLine[];
}

export function buildDailyBrief(input: BriefInput, greetingText: string): DailyBrief {
  const { now } = input;
  const events: BriefLine[] = eventsOn(input.events, now).map((e) => ({
    time: e.allDay ? "כל היום" : formatTime(e.start),
    text: e.title,
    ref: { type: "event", id: e.id },
  }));
  const importantTasks: BriefLine[] = tasksForToday(input.tasks, now)
    .slice(0, 6)
    .map((t) => ({ text: t.title + (t.dueTime ? ` (${t.dueTime.slice(0, 5)})` : ""), ref: { type: "task", id: t.id } }));
  const waiting: BriefLine[] = input.waiting
    .filter((w) => w.status === "open")
    .slice(0, 6)
    .map((w) => ({
      text: `${w.person} — ${w.subject}${w.expectedResponseDate && w.expectedResponseDate <= toDateKey(now) ? " (עבר המועד)" : ""}`,
      ref: { type: "waiting_for", id: w.id },
    }));
  const attention: BriefLine[] = [];
  for (const t of overdueTasks(input.tasks, now)) attention.push({ text: `באיחור: ${t.title}`, ref: { type: "task", id: t.id } });
  const todays = eventsOn(input.events, now).filter((e) => !e.allDay);
  for (let i = 1; i < todays.length; i++) {
    if (todays[i].start < todays[i - 1].end) {
      attention.push({ text: `התנגשות: "${todays[i - 1].title}" ו"${todays[i].title}"`, ref: { type: "event", id: todays[i].id } });
    } else if (minutesBetween(todays[i - 1].end, todays[i].start) < 10) {
      attention.push({ text: `אין הפסקה בין "${todays[i - 1].title}" ל"${todays[i].title}"`, ref: { type: "event", id: todays[i].id } });
    }
  }
  return { date: toDateKey(now), greeting: greetingText, events, importantTasks, waiting, attention };
}

export function dailyBriefToText(b: DailyBrief): string {
  const lines: string[] = [`${b.greeting}.`, ""];
  lines.push("היום:");
  lines.push(...(b.events.length ? b.events.map((e) => `${e.time} – ${e.text}`) : ["אין אירועים ביומן."]));
  if (b.importantTasks.length) lines.push("", "משימות חשובות:", ...b.importantTasks.map((t) => `• ${t.text}`));
  if (b.waiting.length) lines.push("", "ממתינים לתשובה:", ...b.waiting.map((w) => `• ${w.text}`));
  if (b.attention.length) lines.push("", "דברים שכדאי לשים לב אליהם:", ...b.attention.map((a) => `• ${a.text}`));
  return lines.join("\n");
}

/**
 * One-glance body for the morning-brief notification, from real records only:
 * "3 פגישות, הראשונה 09:30 ישיבת צוות · 2 משימות: דוח רבעוני, להתקשר לדני · 1 ממתין לתשובה".
 */
export function morningBriefBody(input: Omit<BriefInput, "now">, day: Date): string {
  const parts: string[] = [];
  const meetings = eventsOn(input.events, day).filter((e) => !e.allDay && e.busy);
  if (meetings.length) {
    const first = meetings[0];
    parts.push(`${meetings.length === 1 ? "פגישה אחת" : `${meetings.length} פגישות`}, ${meetings.length === 1 ? "" : "הראשונה "}${formatTime(first.start)} ${first.title}`);
  }
  const tasks = tasksForToday(input.tasks, day);
  if (tasks.length) {
    const top = tasks.slice(0, 2).map((t) => t.title).join(", ");
    parts.push(`${tasks.length === 1 ? "משימה אחת" : `${tasks.length} משימות`}: ${top}${tasks.length > 2 ? "…" : ""}`);
  }
  const waiting = overdueWaiting(input.waiting, day).length;
  if (waiting) parts.push(waiting === 1 ? "דבר אחד ממתין לתשובה" : `${waiting} ממתינים לתשובה`);
  return parts.length ? parts.join(" · ") : "יום פנוי — אין פגישות או משימות דחופות.";
}

export interface EveningReview {
  date: string;
  completed: number;
  planned: number;
  completedTasks: BriefLine[];
  carriedOver: BriefLine[];
  waiting: BriefLine[];
  tomorrowFirst: BriefLine | null;
  tomorrowEvents: number;
}

export function buildEveningReview(input: BriefInput): EveningReview {
  const { now } = input;
  const today = toDateKey(now);
  const completedToday = input.tasks.filter((t) => t.completedAt && toDateKey(new Date(t.completedAt)) === today);
  const stillOpen = tasksForToday(input.tasks, now);
  const tomorrow = addDays(now, 1);
  const tomorrowEvents = eventsOn(input.events, tomorrow).filter((e) => !e.allDay);
  const first = tomorrowEvents[0];
  return {
    date: today,
    completed: completedToday.length,
    planned: completedToday.length + stillOpen.length,
    completedTasks: completedToday.map((t) => ({ text: t.title, ref: { type: "task", id: t.id } })),
    carriedOver: stillOpen.map((t) => ({ text: t.title, ref: { type: "task", id: t.id } })),
    waiting: input.waiting
      .filter((w) => w.status === "open")
      .map((w) => ({ text: `${w.person} — ${w.subject}`, ref: { type: "waiting_for", id: w.id } })),
    tomorrowFirst: first ? { time: formatTime(first.start), text: first.title, ref: { type: "event", id: first.id } } : null,
    tomorrowEvents: tomorrowEvents.length,
  };
}

export function eveningReviewToText(r: EveningReview): string {
  const lines: string[] = [];
  lines.push(r.planned ? `היום השלמת ${r.completed} מתוך ${r.planned} משימות.` : `היום השלמת ${r.completed} משימות.`);
  if (r.carriedOver.length) {
    lines.push(r.carriedOver.length === 1 ? "משימה אחת עוברת למחר." : `${r.carriedOver.length} משימות עוברות למחר.`);
  }
  if (r.waiting.length) {
    const names = [...new Set(r.waiting.map((w) => w.text.split(" — ")[0]))];
    lines.push(`אתה עדיין מחכה לתשובה מ${names.slice(0, 3).join(", ")}${names.length > 3 ? " ועוד" : ""}.`);
  }
  lines.push(r.tomorrowFirst ? `מחר הפגישה הראשונה שלך ב-${r.tomorrowFirst.time}.` : "אין פגישות ביומן למחר.");
  return lines.join("\n");
}
